import {readFile,writeFile} from 'node:fs/promises';
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const suites=[];
for(const [title,file]of [['Original fixture benchmark','benchmark.json'],['Mapped read checks','mapping.json'],['Mapped write checks','writes.json']]){
 const data=JSON.parse(await readFile(new URL(`../reports/${file}`,import.meta.url),'utf8'));
 suites.push({title,data});
}
const count=suites.reduce((n,s)=>n+s.data.results.length,0);
const unexpected=suites.flatMap(s=>s.data.results).filter(r=>r.status!==r.expected).length;
const sections=suites.map(({title,data})=>`<section><h2>${escape(title)}</h2><p>${escape(data.scope)}</p><table><thead><tr><th>Fixture / case</th><th>Expected</th><th>Observed</th><th>Detail</th></tr></thead><tbody>${data.results.map(r=>`<tr class="${r.status===r.expected?'match':'mismatch'}"><td>${escape([r.fixture,r.name??r.variant].filter(Boolean).join(' / '))}</td><td>${escape(r.expected)}</td><td>${escape(r.status)}</td><td>${escape(r.detail)}</td></tr>`).join('')}</tbody></table></section>`).join('');
await writeFile(new URL('../reports/index.html',import.meta.url),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Access regression — synthetic results</title><style>body{font:16px system-ui,sans-serif;color:#183047;background:#f4f7fa;max-width:1100px;margin:40px auto;padding:0 20px}h1{font-size:32px}section{background:white;padding:24px;margin:24px 0;border:1px solid #d4dde7;border-radius:12px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #d4dde7;vertical-align:top}th{background:#eaf0f6}.mismatch{background:#ffe2e2}.summary{font-size:22px;font-weight:700}p{line-height:1.6}code{background:#eaf0f6;padding:3px}footer{padding:24px 0}</style><h1>Access regression</h1><p>Local synthetic benchmark report</p><p class="summary">${count} cases · ${unexpected} unexpected outcomes</p><p>Recorded results from disposable PostgreSQL-compatible fixtures. A deliberate bug is expected to <strong>fail</strong>; malformed setup must never count as protection. Expected outcomes matching is a benchmark result, not proof that an application is secure.</p><p>No production data, customer connections, HTTP/JWT validation, Storage, or Realtime testing. Report generated ${escape(new Date().toISOString())}. See the JSON files for recorded run details. Suite runs may have different timestamps.</p>${sections}<footer>Open locally; this file contains no scripts, remote assets, forms, telemetry, or external requests. Regenerate with <code>npm run report</code>.</footer></html>`);
console.log(`Wrote reports/index.html: ${count} cases, ${unexpected} unexpected outcomes`);
process.exitCode=unexpected?1:0;
